### ISSUE TITLE
Statement of dataset keys - Consider replacing to a more generic statement

### ISSUE THREAD

**Issue by Addalin** [Addalin/pyALiDAn#15]
The [key statement](https://github.com/Addalin/learning_lidar/blob/bf45e5e64cdeec637df75a3a747af7be339ea20c/learning_lidar/learning_phase/data_modules/lidar_data_module.py#L24-#L25) is problematic. If in the loaded CSV file, the keys' order is not the same or there are different keys, then there may be an error loading a value with get_key_val. 

[get_key_val ()](https://github.com/Addalin/learning_lidar/blob/bf45e5e64cdeec637df75a3a747af7be339ea20c/learning_lidar/learning_phase/data_modules/lidar_data_module.py#L98-#L107) - This is a function designed to segment the results/inputs according to certain features, for example, wavelength time of the day, season/month of the year, etc.

**Comment by OmerShubi** [comment]
@Addalin  This was fixed in a previous commit. Can be closed.
